// Generated by "bundle-dts@1.1.4" https://github.com/fishen/bundle-dts#readme."
declare class Keys {
	get(key: string): {
		key: string;
		label: string;
	};
	get keys(): string[];
	get labels(): string[];
	get entries(): {
		key: string;
		label: string;
	}[];
	get KeyA(): string;
	get KeyB(): string;
	get KeyC(): string;
	get KeyD(): string;
	get KeyE(): string;
	get KeyF(): string;
	get KeyG(): string;
	get KeyH(): string;
	get KeyI(): string;
	get KeyJ(): string;
	get KeyK(): string;
	get KeyL(): string;
	get KeyM(): string;
	get KeyN(): string;
	get KeyO(): string;
	get KeyP(): string;
	get KeyQ(): string;
	get KeyR(): string;
	get KeyS(): string;
	get KeyT(): string;
	get KeyU(): string;
	get KeyV(): string;
	get KeyW(): string;
	get KeyX(): string;
	get KeyY(): string;
	get KeyZ(): string;
	get Digit1(): string;
	get Digit2(): string;
	get Digit3(): string;
	get Digit4(): string;
	get Digit5(): string;
	get Digit6(): string;
	get Digit7(): string;
	get Digit8(): string;
	get Digit9(): string;
	get Digit0(): string;
	get Numpad1(): string;
	get Numpad2(): string;
	get Numpad3(): string;
	get Numpad4(): string;
	get Numpad5(): string;
	get Numpad6(): string;
	get Numpad7(): string;
	get Numpad8(): string;
	get Numpad9(): string;
	get Numpad0(): string;
	get BracketLeft(): string;
	get BracketRight(): string;
	get Slash(): string;
	get Backslash(): string;
	get Minus(): string;
	get Equal(): string;
	get Semicolon(): string;
	get Quote(): string;
	get Comma(): string;
	get Period(): string;
	get Backquote(): string;
}
/** Simple KeyMap for a Hotkey */
declare interface KeyMap {
	/** The key code to be listned for */
	key: string;
	/** Does the Alt key need to be pressed at the same time? */
	alt: boolean;
	/** Does the Ctrl key need to be pressed at the same time? */
	ctrl: boolean;
	/** Does the Shift key need to be pressed at the same time? */
	shift: boolean;
}
/** Hotkey Configuration Registration */
declare interface HotkeySetting {
	/** optional: Group to be included in with their own header. Default: General Group */
	group?: string;
	/** Unique variable name to be used in the layout. Recommend: 'module-name.myHotkey' */
	name: string;
	/** Label to be displayed in the layout. This will be localized when injected into the HTML */
	label: string;
	/** The default setting for this hotkey */
	default(): KeyMap;
	/** Function for retrieving the current hotkey setting */
	get(): KeyMap;
	/** Function for saving the new hotkey setting */
	set(value: KeyMap): Promise<KeyMap>;
	/** Function to handle the execution of the hotkey */
	handle(name: string): void;
}
/** Hotkey Group Configuration */
declare interface HotkeyGroup {
	/** Unique name of the group. */
	name: string;
	/** Displayed in the HTML header for the group. */
	label: string;
	/** Optional description of the group */
	description?: string;
}
declare class Hotkeys {
	static readonly keys: Keys;
	/**
	* Registers a new hotkey configuration.
	* @param config Hotkey configuration.
	* @param throwIfExists If true, will throw an error if a config with that name already exists; default true.
	* @returns The ID for the registration, used for De-Registration, or null if it failed to be registered.
	*/
	static registerShortcut(config: HotkeySetting, throwIfExists?: boolean): boolean;
	/**
	* De-registers the keyboard shortcut previously registered via the ID number returned by the `Hotkeys.registerShortcut` function.
	* @param id ID of the Hotkey to be de-registered.
	* @returns true if a handler was found and removed; false if no handler was found for the given key.
	*/
	static deregisterShortcut(name: string): boolean;
	/**
	* Registers a new Settings Group for hotkeys.
	* @param group Group settings, requiring the name and label. Description is optional.
	* @param throwIfExists If true, will throw an error if a group already exists for the given name; default false.
	* @returns true if the group has been registered; otherwise false if the group already exists.
	*/
	static registerGroup(group: HotkeyGroup, throwIfExists?: boolean): boolean;
}
declare global {
	export type Hotkeys = HotkeysModule.Hotkeys;
	export const Hotkeys: typeof HotkeysModule.Hotkeys;
	export type KeyMap = HotkeysModule.KeyMap;
	export type HotkeyGroup = HotkeysModule.HotkeyGroup;
	export type HotkeySetting = HotkeysModule.HotkeySetting;
}
